### ISSUE TITLE
rank and select for IntVector?

### ISSUE THREAD

**Issue by KonradHoeffner** [tov/succinct-rs#16]
I don't see rank and select methods in <https://docs.rs/succinct/0.5.2/succinct/struct.IntVector.html>. Are those contained in another module or is it not possible to perform rank and select on an IntVector in succinct-rs?

**Comment by tov** [comment]
An `IntVector` alone isn't sufficient to do efficient rank/select operations---you need some kind of index.

For rank, see the [`succint::rank`](https://docs.rs/succinct/0.5.2/succinct/rank/index.html) module for two rank support structs, [`JacobsonRank`](https://docs.rs/succinct/0.5.2/succinct/rank/struct.JacobsonRank.html) and [Rank9](https://docs.rs/succinct/0.5.2/succinct/rank/struct.Rank9.html).

If you need select, you can construct a [`succint::select::BinSearchSelect`](https://docs.rs/succinct/0.5.2/succinct/select/struct.BinSearchSelect.html) on top of your rank structure.
